### PR TITLE
Implement Target Metadata

### PR DESCRIPTION
**Pull request by hjkatz**
## What
*Describe what the change is solving*

Implement propagating the target metadata (annotations and labels) to the target service created by BoundEndpoint

## How
*Describe the solution*

Add util.ParseHelmDictionary()

Use util.ParseHelmDictionary() for --ngrok-metadata

Add serviceAnnotations and serviceLabels flags to api binary

Propagate target metadata to target service

## Breaking Changes
*Are there any breaking changes in this PR?*
No.

### CODE REVIEW

**Comment by hjkatz** [comment]
* **#477** <a href="https://app.graphite.dev/github/pr/ngrok/ngrok-operator/477?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @hjkatz and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by hjkatz** [comment]
@jonstacks I chose not to factor out the config file for the api binary for simplicity in implementing the metadata for now.

We can always go back and use a config file for settings.

**Comment by jonstacks** [comment]
> @jonstacks I chose not to factor out the config file for the api binary for simplicity in implementing the metadata for now.
> 
> We can always go back and use a config file for settings.

Sounds good to me. I've logged https://github.com/ngrok/ngrok-operator/issues/478 for simplifying the config

**Review by jonstacks — APPROVED** [review]

**Comment by hjkatz** [comment]
### Merge activity

* **Oct 30, 12:40 PM EDT**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/ngrok/ngrok-operator/477).

**Pull request merged**
